from pathlib import Path

from sqlalchemy import create_engine, text

SCHEMA_SQLITE = Path("sql/schema.sql")
SCHEMA_POSTGRES = Path("sql/schema_postgres.sql")


def _apply(engine, path: Path) -> None:
    statements = [
        s.strip() for s in path.read_text(encoding="utf-8").split(";") if s.strip()
    ]
    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(stmt))


def test_sqlite_schema_has_no_drop_table():
    content = SCHEMA_SQLITE.read_text(encoding="utf-8")
    assert "DROP TABLE" not in content.upper()


def test_sqlite_schema_applies_twice_idempotently():
    engine = create_engine("sqlite:///:memory:")
    _apply(engine, SCHEMA_SQLITE)
    _apply(engine, SCHEMA_SQLITE)  # 重複套用不可報錯
    with engine.begin() as conn:
        tables = conn.execute(
            text("SELECT name FROM sqlite_master WHERE type='table'")
        ).scalars().all()
    for expected in ["teams", "players", "player_match_stats", "matches"]:
        assert expected in tables


def test_sqlite_schema_has_season_columns():
    engine = create_engine("sqlite:///:memory:")
    _apply(engine, SCHEMA_SQLITE)
    with engine.begin() as conn:
        for table in ["players", "player_match_stats", "matches"]:
            cols = [row[1] for row in conn.execute(text(f"PRAGMA table_info({table})"))]
            assert "season" in cols, f"{table} 缺少 season 欄位"


def test_postgres_schema_has_no_sqlite_specific_syntax():
    content = SCHEMA_POSTGRES.read_text(encoding="utf-8")
    assert "AUTOINCREMENT" not in content
    assert "GENERATED BY DEFAULT AS IDENTITY" in content
    for table in ["teams", "players", "player_match_stats", "matches"]:
        assert f"CREATE TABLE IF NOT EXISTS {table}" in content
