import re
from pathlib import Path

from sqlalchemy import create_engine, text

SCHEMA_SQLITE = Path("sql/schema.sql")
SCHEMA_POSTGRES = Path("sql/schema_postgres.sql")


def _split_top_level(body: str) -> list[str]:
    """依逗號分割，但忽略括號（例如 CHECK (...)）內的逗號。"""
    parts, current, depth = [], [], 0
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return [p.strip() for p in parts if p.strip()]


def _parse_tables(path: Path) -> dict[str, dict]:
    """解析 schema 檔，回傳 {table_name: {"columns": [...], "uniques": [(...), ...]}}。
    僅比對欄位名稱與 UNIQUE 約束，忽略型別/AUTOINCREMENT 與 GENERATED ... IDENTITY 這類
    SQLite/PostgreSQL 語法差異。
    """
    content = "\n".join(
        line for line in path.read_text(encoding="utf-8").splitlines()
        if not line.strip().startswith("--")
    )
    tables: dict[str, dict] = {}
    for stmt in [s.strip() for s in content.split(";") if s.strip()]:
        m = re.match(
            r"CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\((.*)\)\s*$",
            stmt, re.DOTALL | re.IGNORECASE,
        )
        if not m:
            continue
        table_name, body = m.group(1), m.group(2)
        columns, uniques = [], []
        for segment in _split_top_level(body):
            upper = segment.upper()
            if upper.startswith("UNIQUE"):
                inner = re.search(r"\((.*)\)", segment, re.DOTALL)
                uniques.append(tuple(c.strip() for c in inner.group(1).split(",")))
            elif upper.startswith(("PRIMARY KEY", "FOREIGN KEY", "CHECK")):
                continue
            else:
                columns.append(segment.split()[0])
        tables[table_name] = {"columns": columns, "uniques": uniques}
    return tables


def _apply(engine, path: Path) -> None:
    statements = [
        s.strip() for s in path.read_text(encoding="utf-8").split(";") if s.strip()
    ]
    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(stmt))


def test_sqlite_schema_has_no_drop_table():
    content = SCHEMA_SQLITE.read_text(encoding="utf-8")
    assert "DROP TABLE" not in content.upper()


def test_sqlite_schema_applies_twice_idempotently():
    engine = create_engine("sqlite:///:memory:")
    _apply(engine, SCHEMA_SQLITE)
    _apply(engine, SCHEMA_SQLITE)  # 重複套用不可報錯
    with engine.begin() as conn:
        tables = conn.execute(
            text("SELECT name FROM sqlite_master WHERE type='table'")
        ).scalars().all()
    for expected in ["teams", "players", "player_match_stats", "matches"]:
        assert expected in tables


def test_sqlite_schema_has_season_columns():
    engine = create_engine("sqlite:///:memory:")
    _apply(engine, SCHEMA_SQLITE)
    with engine.begin() as conn:
        for table in ["players", "player_match_stats", "matches"]:
            cols = [row[1] for row in conn.execute(text(f"PRAGMA table_info({table})"))]
            assert "season" in cols, f"{table} 缺少 season 欄位"


def test_postgres_schema_has_no_sqlite_specific_syntax():
    content = SCHEMA_POSTGRES.read_text(encoding="utf-8")
    assert "AUTOINCREMENT" not in content
    assert "GENERATED BY DEFAULT AS IDENTITY" in content
    for table in ["teams", "players", "player_match_stats", "matches"]:
        assert f"CREATE TABLE IF NOT EXISTS {table}" in content


def test_sqlite_and_postgres_schema_structural_parity():
    """兩份 schema 檔的四張表欄位集合（含順序）與 UNIQUE 約束須完全一致，避免其中一份漏改而產生 drift。"""
    sqlite_tables = _parse_tables(SCHEMA_SQLITE)
    postgres_tables = _parse_tables(SCHEMA_POSTGRES)
    expected_tables = {"teams", "players", "player_match_stats", "matches"}
    assert set(sqlite_tables) == expected_tables
    assert set(postgres_tables) == expected_tables

    for table in expected_tables:
        assert sqlite_tables[table]["columns"] == postgres_tables[table]["columns"], (
            f"{table} 欄位集合不一致：sqlite={sqlite_tables[table]['columns']} "
            f"postgres={postgres_tables[table]['columns']}"
        )
        assert sqlite_tables[table]["uniques"] == postgres_tables[table]["uniques"], (
            f"{table} UNIQUE 約束不一致"
        )
